-- AlterTable
ALTER TABLE "public"."ListProducts" ALTER COLUMN "stock" SET DEFAULT 0,
ALTER COLUMN "stock" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "public"."Products" ALTER COLUMN "stock" SET DEFAULT 0,
ALTER COLUMN "stock" SET DATA TYPE DECIMAL(65,30);
